### PR TITLE
Initial QA section

### LINKED ISSUE #4: Assumptions log
need a record of what assumptions are in the model and the basis of these decisions

### PR DESCRIPTION
**Pull request by StatsRhian**
Collating the QA into a new QA section, adding an assumptions log. (Closes #4 )

Also sets `echo: false` as default chunk execution

### CODE REVIEW

**Comment by StatsRhian** [comment]
From existing QA page:

## External Review Actions

Specific areas for further reviews were highlighted and these were added to the QA plan:

* Consideration on dealing with systemic effects... warn users that uncertainty assigned to individual strategies may not reflect fully in uncertainty (e.g. 90% CI) of full-run, in case their view of pessimistic and optimistic ends of the range relates to a correlated scenario (e.g. widespread funding cuts; workforce constraints)
* Consideration on interactions between strategies (second order), whether because they interact in terms of odds of implementation or on odds of effectiveness
* Further lay language on known limits of the model to model operators, e.g. lack of stock and flow modelling of beds
* Further actions on ensuring that users understand the level of uncertainty associated with input parameters as opposed to uncertainty associated with monte carlo noise

@yiwen-h Have any of these been done since this was written? If not, are should I add them all to the QA plan - or are there some which we won't implement?

**Comment by StatsRhian** [comment]
# Where to add general processes?

We do a number of things in our processes for developing/releasing the model and onboarding trusts. 
Where should we document this? It doesn't feel like it fits into assumptions log, QA log or plan? Where should it live? Just a page on the project information?

## Code development

- GitHub Actions
- PR review
- Release checklists

## Onboarding trusts

The following parameters are set by individual trusts

* Baseline adjustments
* Population changes
* Waiting list imbalances
* Expatriation/ repatriation
* Inequalities
* Activity mitigators
* Bed occupancy

In all cases these parameters are set after an extensive support process from a team allied to the team building the model, and the parameters are set with appropriate involvement of stakeholders and with governance processes as determined locally.

Data is further verified by consistency checks carried out by hospital trusts using the model. Information about their baseline activity is provided to trusts and they are able to check their own records of activity against the data used in the model. Any inconsistencies are explored and resolved with each trust before the model is run.

**Comment by StatsRhian** [comment]
# Assumptions table columns

- Could add a one sentence description justifying the reasons for the quality and impact ratings in the json / table
- Could show quality as [1-3 stars like this](https://connect.strategyunitwm.nhs.uk/modeling-changes-in-population-health-status/model-pop-health-status.html)
- Are we okay with the words (High, Medium, Low, Excellent, Good, Poor?)
- Do we need risk rating? Drop it?

**Comment by StatsRhian** [comment]
This was getting big so I moved the processes stuff out to a new issue (#48)
I kept the diagram in QA for now
Also added a few extra links and copied the role and responsibilities from the original QA submition.

Ready for review (thank you!)

**Review by yiwen-h — APPROVED** [review]

**Pull request merged**
